### ISSUE TITLE
Important message in Toast is cut if the message is long

### ISSUE THREAD

**Issue by boilund** [AxisCommunications/practical-react-components#16]
It happens that the important message in Toast is cut out when the message is longer than the toast width. So we would like to solve this problem in some way. 

- add tooltips to the overflow text ??
- allow multiple lines ??

![image](https://user-images.githubusercontent.com/24866179/106253474-cf806480-6217-11eb-915d-a3c7efda17ee.png)

**Comment by anius** [comment]
IMO this is correct behaviour as `label` should show only key words (like a header in the newspaper), like `Warning`, `Info`, `Oops, something went wrong` and then you show a detailed info in the toast's `message`.

**Comment by boilund** [comment]
Thank you for your comment, @anius. And I understand what you think.

But this issue is reported by UX designer and I think it´s not so bad idea we support this issue somehow. Because it could be happen in some language even if the text in English fits in the Toast. 

Also I think we can support this issue with Tooltip like we supported Dialog header with Tooltip before. 
Actually we tested to add Tooltip to the Toast label at our mob last week. So I think @Tigge is agree with this change.

**Comment by anius** [comment]
😢 UX designer could be wrong as well, UX designer is still just a person like everyone else 😃 
IMO in your case the text should be moved to `message` property but feel free to ignore my comment😃  

<img width="1229" alt="Screenshot 2021-02-17 at 18 39 03" src="https://user-images.githubusercontent.com/2505557/108244399-78ebb380-714f-11eb-91ae-6ab7f41ef5be.png">

**Comment by lekoaf** [comment]
I agree with @anius here. ToastLabel is not for long messages. They should be short and to the point. Any further description should be added to a ToastMessage.

**Comment by steabert** [comment]
It feels strange to have tooltips on a header of a notification toast, then I would just not let it overflow but allow it to wrap instead.

The biggest problem with "tooltip on overflow" is that it's technically unfeasible to do this in any automatic way, and adding this feature everywhere is going to be a nightmare. I mean, this can happen in every component.

**Comment by anius** [comment]
Not really sure why you don't want to use `message` prop for the Toast 😃 , then you won't need to care about overflow at all:

<img width="402" alt="Screenshot 2021-02-18 at 08 36 11" src="https://user-images.githubusercontent.com/2505557/108321495-898a4100-71c4-11eb-816b-02d4a3d2bc8c.png">

**Comment by boilund** [comment]
It was decided to allow two rows label in Toast. So I added PR for this.
