### ISSUE TITLE
Consider releasing v1.0 for easier peerDependencies handling

### ISSUE THREAD

**Issue by anius** [AxisCommunications/practical-react-components#184]
I'm using this package in some of my internal packages which has it as `peerDependencies` but as the version is `0`, e.g., `0.56.0` I'm not able to handle this in a nice way and have this packages as `^0.x` in `peerDependencies` as per [documentation](https://github.com/npm/node-semver#caret-ranges-123-025-004) but if some version has breaking changes than I'm in trouble.

As per link above:

- ^1.2.3 := >=1.2.3 <2.0.0-0
- ^0.2.3 := >=0.2.3 <0.3.0-0
- ^0.0.3 := >=0.0.3 <0.0.4-0
- ^1.x := >=1.0.0 <2.0.0-0
- ^0.x := >=0.0.0 <1.0.0-0

using v1.0 will make easier handling of this package in `peerDependencies`

**Comment by lekoaf** [comment]
I agree. Using 0.X.X versions obfuscates breaking changes in an undesirable way. Let's be more transparent.

**Comment by Tigge** [comment]
Yeah, I think we can deem this stable enough for a 1.0.0 release. That however means we have to be more careful with marking changes as breaking. Perhaps we could use require the use the `yarn version --deferred` for each PR?

**Comment by lekoaf** [comment]
@Tigge do it!
