### ISSUE TITLE
Question: why dependencies and not peerDependencies

### ISSUE THREAD

**Issue by anius** [AxisCommunications/practical-react-components#186]
Why you use `dependencies` and not `peerDependencies` in the non-private packages in this repository, for example https://github.com/AxisCommunications/practical-react-components/blob/main/packages/core/package.json#L11?

Currently this repo forces exact dependencies when using its packages, wouldn't it be easier for the users if these dependencies were changed to `peerDependencies` with the required working range so the users can update the dependencies without a need for the repository to update them, for example when a bug is fixed in one of them?

**Comment by Tigge** [comment]
Yeah, this should definitely be fixed. They should at least not be version pinned. Not sure if it makes sense to change them to peer dependencies, but I don't have a strong opinion on that.
