### ISSUE TITLE
A help icon button in the header with some weird content

### ISSUE THREAD

**Issue by anius** [AxisCommunications/practical-react-components#40]
A new question mark icon appeared in the header which is probably supposed to show some help dialog but currently a dialog with some weird content is show:

<img width="269" alt="Screenshot 2021-02-16 at 10 33 45" src="https://user-images.githubusercontent.com/2505557/108044547-b0206e80-7042-11eb-96cb-6fc9637ea2cd.png">
<img width="1321" alt="Screenshot 2021-02-16 at 10 33 52" src="https://user-images.githubusercontent.com/2505557/108044556-b282c880-7042-11eb-91b9-d122850a1c1d.png">

Expected behaviour:
- Help dialog with some help texts when clicking on the help icon in the header

Current behaviour:
- A dialog with some weird content when clicking on the help icon in the header

**Comment by lekoaf** [comment]
That's supposed to include the licenses. Seems like something went wrong @Tigge.

**Comment by Tigge** [comment]
Thanks! This is now fixed with in 5384d0733b428ea1fc2a009fe19ea2ba6c96926b and should be live by now.
